### ISSUE TITLE
Translate artistit.json keys to english (and in-app references)

### ISSUE THREAD

**Issue by mkirvela** [futurice/festapp-android#12]
New keys are:
"id", "name", "picture", "quote", "content", "featured", "status", "stage", "day", "time_start", "time_stop", "founded", "genre", "members", "albums", "highlights", "youtube", "spotify", "contact_info", "press_image", "credits", "place"

**Comment by ktuukkan** [comment]
Existing local JSON fields fixed with english field names. JSONs are loaded on startup but still unsure if the app actually fetches anything from the web?

**Comment by wijnbladh** [comment]
I'm thinking this came in with the pull request (#36) from ktuukkan, and is found in the commit: 9a156f19959b9db9497d6446ab6e2b5ddf0afb44
