### ISSUE TITLE
Clean old TODOs, compiler warnings, etc.

### ISSUE THREAD

**Issue by wijnbladh** [futurice/festapp-android#14]
Check all TODO-comments, remove or fix as needed.

Also, there is some 37 compiler warnings, such as unused imports, and unclosed resources. Check and fix.

**Comment by joelmertanen** [comment]
TODOs are handled at #10

**Comment by wijnbladh** [comment]
hleh fixed majority of compiler warnings in 85af8f89868e14e3ab741d6f5b6aa3942d48f89f. There is two left now. Let's handle them later on.
