### ISSUE TITLE
FestivalDay enum

### ISSUE THREAD

**Issue by hleh** [futurice/festapp-android#18]
enum needs to be refactored

**Comment by sorja** [comment]
Robotti3 has taken over this issue

**Comment by pahuttun** [comment]
More information about issue:

Check issue #46, it is related to this: https://github.com/futurice/festapp-android/issues/46

Biggest problems with FestivalDay enum are following:
- Finnish text in code. You should fetch finnish texts from string resources (strings.xml)
- Hard coded 3 day festival from friday to sunday. Issue #46 is more about this
