### ISSUE TITLE
Replace word 'ruisrock' with 'festapp' in everywhere

### ISSUE THREAD

**Issue by joelmertanen** [futurice/festapp-android#2]

**Comment by wijnbladh** [comment]
OBS: Could start with package names:

fi.ruisrock.android.\* -> com.futurice.festapp.*

**Comment by jvah** [comment]
com.futurice.festapp is also used on iOS

**Comment by ktuukkan** [comment]
Android packaging renamed, continuing with 'ruisrock' search/replace.

**Comment by ktuukkan** [comment]
Resolved by pull request #25.
