### ISSUE TITLE
Data from JSON not showing up for Info->Information->Info stand [easy/medium]

### ISSUE THREAD

**Issue by wijnbladh** [futurice/festapp-android#44]
Message for info stand does no show up in UI, steps to repeat:
- On main screen, select INFO
- Then select INFORMATION
- Then select "Info stand"
- The view that opens should show text "Where you can find the infostand", but shows no text apart from header.

The content should come from the file: res/raw/general_info.json, and obviously from backend at some point.

**Comment by wijnbladh** [comment]
Same thing for the menu items "Ticket sales" and "Safety instructions" in the same view. Chances are the initial JSON file is lacking some of the expected data.

**Comment by pahuttun** [comment]
Fixed with pull request #62
