### ISSUE TITLE
Replace hard-coded texts with generic place-holders

### ISSUE THREAD

**Issue by ktuukkan** [futurice/festapp-android#5]
There's a number of menu items etc. with hard-coded labels. These must be replaced with generic place-holders. When possible, place-holders should not identity any purpose or origin of the app. Later, the place-holders should also be made configurable from external property files or backend.

**Comment by wijnbladh** [comment]
Arrived in pull request from ttur. Commited in caf82dd598165716691eba652fd1e95948260387.
