### ISSUE TITLE
Add a mechanism for forcing data fetch from the back-end [easy/medium]

### ISSUE THREAD

**Issue by wijnbladh** [futurice/festapp-android#50]
The app uses ETags (http://en.wikipedia.org/wiki/HTTP_ETag) to figure out whether it should re-fetch certain data or not. See method isContentUpdated(...) in HTTPUtil.java.

Add a mechanism that allows this data fetch to be forced. This serves the case where a developer just wants to see that the data fetch takes place, so it is a developer tool or utility.

The mechanism might be something like:
- A boolean value that the developer can set in the code. If the value is true, the whole ETag business is skipped.
- A UI element, visible only in some "DEV" mode (i.e. hidden in "production" builds), that can be clicked to force the data fetching.

**Comment by ljleppan** [comment]
Robot 2 claims this issue for the greater good of all mankind

**Comment by wijnbladh** [comment]
Implemented in commit 82fdf655148f53d93d3a5c4961e02783fea4f37a, in pull request #65. See FestAppConstants.java for debug constants.
